Bideas\CsvToTei\Model\Change:
    properties:
        when:
            type: string
            xml_attribute: true
        date:
            type: string
            serialized_name: date
            xml_element:
                cdata: false
        name:
            type: string
            serialized_name: name
            xml_element:
                cdata: false
        list:
            type: Bideas\CsvToTei\Model\ListOfItems
            serialized_name: list