Bideas\CsvToTei\Model\Availability:
    properties:
        status:
            type: string
            xml_attribute: true
        p:
            type: array<string>
            serialized_name: p
            xml_list:
                inline: true
                entry_name: p
            xml_element:
                cdata: false
        licence:
            type: string
            serialized_name: licence
        ab:
            type: string
            serialized_name: ab