Bideas\CsvToTei\Model\FileDesc:
    properties:
        editionStmt:
            serialized_name: editionStmt
            type: string
        extent:
            serialized_name: extent
            type: string
        notesStmt:
            serialized_name: notesStmt
            type: string
        publicationStmt:
            serialized_name: publicationStmt
            type: string
        seriesStmt:
            serialized_name: seriesStmt
            type: string
        sourceDesc:
            serialized_name: sourceDesc
            type: string
        titleStmt:
            serialized_name: titleStmt
            type: string