Bideas\CsvToTei\Model\TeiHeader:
    properties:
        encodingDesc:
            type: 'Bideas\CsvToTei\Model\EncodingDesc'
            serialized_name: encodingDesc
        fileDesc:
            type: 'Bideas\CsvToTei\Model\FileDesc'
            serialized_name: fileDesc
        profileDesc:
            type: string
            serialized_name: profileDesc
        revisionDesc:
            type: Bideas\CsvToTei\Model\RevisionDesc
            serialized_name: revisionDesc
        xenoData:
            type: string
            serialized_name: xenoData