Bideas\CsvToTei\Model\TitleStmt:
    properties:
        author:
            type: string
            serialized_name: author
        editor:
            type: string
            serialized_name: editor
        meeting:
            type: string
            serialized_name: meeting
        respStmt:
            type: 'Bideas\CsvToTei\Model\RespStmt'
            serialized_name: respStmt
        title:
            type: string
            serialized_name: title
            xml_element:
                  cdata: false