Bideas\CsvToTei\Model\TeiHeader:
    properties:
        encodingDesc:
            serialized_name: encodingDesc
            type: string
        fileDesc:
            serialized_name: fileDesc
            type: string
        profileDesc:
            serialized_name: profileDesc
            type: string
        revisionDesc:
            serialized_name: revisionDesc
            type: string
        xenoData:
            serialized_name: xenoData
            type: string