Bideas\CsvToTei\Model\Ref:
    properties:
        target:
            type: string
            xml_attribute: true
        value:
            type: string
            xml_value: true
            xml_element:
                cdata: false