Bideas\CsvToTei\Model\FileDesc:
    properties:
        editionStmt:
            type: string
            serialized_name: editionStmt
        extent:
            type: string
            serialized_name: extent
        notesStmt:
            type: string
            serialized_name: notesStmt
        publicationStmt:
            type: string
            serialized_name: publicationStmt
        seriesStmt:
            type: string
            serialized_name: seriesStmt
        sourceDesc:
            type: string
            serialized_name: sourceDesc
        titleStmt:
            type: 'Bideas\CsvToTei\Model\TitleStmt'
            serialized_name: titleStmt