Bideas\CsvToTei\Model\ListOfItems:
    properties:
        item:
            type: array<string>
            serialized_name: item
            xml_list:
                inline: true
                entry_name: item
            xml_element:
                cdata: false