Bideas\CsvToTei\Model\Tei:
    xml_root_name: TEI
    xml_root_namespace: http://www.tei-c.org/ns/1.0
    properties:
        teiHeader:
            type: 'Bideas\CsvToTei\Model\TeiHeader'
            serialized_name: teiHeader
        texts:
            type: string
            serialized_name: texts