Bideas\CsvToTei\Model\FileDesc:
    properties:
        editionStmt:
            type: 'Bideas\CsvToTei\Model\editionStmt'
            serialized_name: editionStmt
        extent:
            type: string
            serialized_name: extent
            xml_element:
                cdata: false
        notesStmt:
            type: 'Bideas\CsvToTei\Model\notesStmt'
            serialized_name: notesStmt
        publicationStmt:
            type: 'Bideas\CsvToTei\Model\publicationStmt'
            serialized_name: publicationStmt
        seriesStmt:
            type: string
            serialized_name: seriesStmt
        sourceDesc:
            type: 'Bideas\CsvToTei\Model\SourceDesc'
            serialized_name: sourceDesc
        titleStmt:
            type: 'Bideas\CsvToTei\Model\TitleStmt'
            serialized_name: titleStmt