Bideas\CsvToTei\Model\SourceDesc:
    properties:
        p:
            type: array<string>
            serialized_name: p
            xml_list:
                inline: true
                entry_name: p
            xml_element:
                cdata: false